### ISSUE TITLE
404 Not Found: Requested route ('spring.io') does not exist

### ISSUE THREAD

**Issue by lingocoder** [spring-guides/getting-started-guides#101]
None of the [*Getting Started guides*](https://spring.io/guides/gs/multi-module/) exist at spring.io anymore.

Attempting to access _**anything**_ at spring.io, results in a „*`404 Not Found: Requested route ('spring.io') does not exist`*“ error:

![spring guides issue 101 0](https://user-images.githubusercontent.com/49788472/58590132-eefd0800-8252-11e9-84ae-6168c7ca5cd2.png)

**Comment by dsyer** [comment]
https://twitter.com/springops/status/1133823351565238273
