### ISSUE TITLE
Accessing Data with MongoDB article needs improvements

### ISSUE THREAD

**Issue by farazdurrani** [spring-guides/getting-started-guides#106]
The startup guide at [Accessing Data with MongoDB](https://spring.io/guides/gs/accessing-data-mongodb/) requires some improvements. For example, there is no place for this paragraph in the write-up:
>Normally you would add @EnableWebMvc for a Spring MVC app, but Spring Boot adds it automatically when it sees spring-webmvc on the classpath. This flags the application as a web application and activates key behaviors such as setting up a DispatcherServlet.

This is because that write-up is not about serving HTTP requests. It has nothing to do with serving content to the user. And there is no Spring boot starter web dependency on the classpath of the article. 

Instead, it should be replaced with something like this:
>Spring boot application will automatically enable @EnableMongoRepositories as it found spring-boot-starter-data-mongodb on the classpath. 

Something like that.

**Comment by dsyer** [comment]
Fixed here: https://github.com/spring-guides/getting-started-macros/commit/5034bdddd8fb73b87ca7dea0d77dd2d921762ab6. Actually there is no content specifically on `@EnableMongoRepositories`, but please raise issues directly in the Mongo guide repo if you think there should be.

**Comment by farazdurrani** [comment]
How can I do that? Where is Mongo guide repo?

**Comment by dsyer** [comment]
https://github.com/spring-guides/gs-accessing-data-mongodb

**Comment by farazdurrani** [comment]
Thank you @dsyer 

[Issue raised.](https://github.com/spring-guides/gs-accessing-data-mongodb/issues/30)
