### ISSUE TITLE
Accessing MongoDB Data with REST - page not found

### ISSUE THREAD

**Issue by toropov023** [spring-guides/getting-started-guides#119]
Page not found navigating from the [Accessing Data with MongoDB](https://spring.io/guides/gs/accessing-data-mongodb/) page.

Missing content URL: https://spring.io/gs/accessing-mongodb-data-rest

**Comment by dsyer** [comment]
Looks Ok now. Stale cache I think

**Comment by toropov023** [comment]
Still seems to be having issue with this one

**Comment by dsyer** [comment]
Works for me. I guess that’s caching for you.

**Comment by toropov023** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fspring.io%2Fgs%2Faccessing-mongodb-data-rest

**Comment by dsyer** [comment]
Wrong URL? What are you trying to say.

**Comment by toropov023** [comment]
Sorry I thought it was clear. What I'm saying is that it's not my caching, the url (https://spring.io/gs/accessing-mongodb-data-rest) is not found and you can verify this with the pagespeed tool: error 404

You can try any other tool, but the page is not found.

**Comment by dsyer** [comment]
Well, yes, but that isn't the URL of any guide on spring.io. Did you mean https://spring.io/guides/gs/accessing-mongodb-data-rest (which is not a 404)? The code snippets look OK there too to me. Let us know what you find.

**Comment by toropov023** [comment]
Ah I see! Thank you pointing out the correct url. I followed that link from the bottom of the Accessing Data with MongoDB page (https://spring.io/guides/gs/accessing-data-mongodb/). So I'm guessing that link just needs a tiny fix

**Comment by dsyer** [comment]
Thanks. Link fixed https://github.com/spring-guides/gs-accessing-data-mongodb/commit/5bafc835b4b5ad0dad12c1fae5c5e8a408f17136.
