### ISSUE TITLE
[Building a Gateway] f.circuitbreaker instead of f.circuitBreaker

### ISSUE THREAD

**Issue by vinsse2001** [spring-guides/getting-started-guides#146]
Hi !
In tutorial "[Building a Gateway](https://spring.io/guides/gs/gateway/)", the example code shows f.circuitbreaker(..., but in [github](https://github.com/spring-guides/gs-gateway/blob/main/complete/src/main/java/gateway/Application.java), we can see it with "B" upcase (circuitBreaker).
There are 2 to correct.
Thanks !

**Comment by ryanjbaxter** [comment]
This is the wrong repo for this issue
