### ISSUE TITLE
Apache Kafka Guide for Spring Boot

### ISSUE THREAD

**Issue by MihSawant** [spring-guides/getting-started-guides#152]
I would like to contribute for Apache Kafka messaging service for Spring Boot

**Comment by MihSawant** [comment]
It would be a sample application and explain the broker, producer, consumer and topic

**Comment by kunalvarpe** [comment]
@MihSawant Are you working on this? I would also love to contribute here, let me know we we can do it toghether.

**Comment by robertmcnees** [comment]
Closing as a duplicate of #72
