### ISSUE TITLE
Building REST services with Spring - Guide: Outdated package dependencies

### ISSUE THREAD

**Issue by CK-Steve** [spring-guides/getting-started-guides#161]
In the provided Code for the Employee Class, the Article shows import of "javax.persistence.Entity" and so on: 
Following this [Article](https://stackoverflow.com/a/74996933) i found out that instead you need to import jakarta.persistence.* ...

**Comment by robertmcnees** [comment]
Hi @CK-Steve. I assume that you're referring to [this tutorial](https://spring.io/guides/tutorials/rest). You are correct that our code does have an error by importing the wrong packages.

I will close this issue as a duplicate, as we are tracking it through [this issue](https://github.com/spring-guides/tut-rest/issues/116). As a reminder, if you find issues with specific guides please try to submit the issues in that repository. Feel free to follow along and contribute in the linked issue.  Thanks for calling this out.
