### ISSUE TITLE
Create Guide for Spring boot and Apache Camel

### ISSUE THREAD

**Issue by jayho** [spring-guides/getting-started-guides#23]
Guide that shows how Apache Camel integrates with Spring boot. Create a small ETL example that uses a simple Camel route (also mention logging and monitoring). See also http://camel.apache.org/spring-boot.html

Do you think this would be of interest as a new guide?

**Comment by gregturn** [comment]
Thanks for your request @jayho, but I think this request would be better served in Apache Camel's documentation and learning resources.
