### ISSUE TITLE
Authenticating a User with LDAP guide has multiple errors

### ISSUE THREAD

**Issue by chaitanyathengdi** [spring-guides/getting-started-guides#25]
The 'Authenticating a User with LDAP' guide - https://spring.io/guides/gs/authenticating-ldap/ has some errors that need to be corrected:

1. The 'Application.java' class definition is repeated with no difference between the two; so the second one is unnecessary.

2. The 'WebSecurityConfig.java' class has incorrect annotations used, which are now deprecated. The annotations below the code(i.e. in the description) are correct, but in the code are wrong.

Wrong import:
import org.springframework.security.config.annotation.web.servlet.configuration.EnableWebMvcSecurity;

Correct import:
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;

Also the annotation 'EnableWebMvcSecurity' on line 11 needs to be changed accordingly.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-authenticating-ldap/commit/e2bee44edfbaa38434b592e45f12c3f70646f046
