### ISSUE TITLE
The guide "Accessing Data with Neo4j" skipped the source code

### ISSUE THREAD

**Issue by Fr3man** [spring-guides/getting-started-guides#27]
Thanks for the excellent introduction for Neo4j.
Could you please add the source code of ApplicationConfig class to the guide?
I was a bit coufused when ./gradlew bootRun threw an UnsatisfiedDependencyException caused by missed ApplicationConig class with Neo4j annotations.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-accessing-data-neo4j/commit/575f44631018f0e34b6072971aac8a59380fb6dc

**Comment by Fr3man** [comment]
Thanks for quick response)
