### ISSUE TITLE
Default value for "required" param in @RequestMapping annotation

### ISSUE THREAD

**Issue by david-arteaga** [spring-guides/getting-started-guides#33]
The guide at https://spring.io/guides/gs/rest-service/ and the docs (http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestParam.html#required--) say that the "required" param in the org.springframework.web.bind.annotation.RequestMapping annotation has a default value of false.
In spite of that, when I run a project without specifying a value it defaults to true.
In netbeans, when I checked the downloaded sources from Maven, the default is set to true.

There seems to be a contradiction there.

![image](https://cloud.githubusercontent.com/assets/7199015/18688661/f26bfec8-7f4a-11e6-8aff-625ba8a9a4e6.png)

**Comment by dsyer** [comment]
The javadoc says "true" is the default for the required attribute of `@RequestParam`. But I'm not sure I know what you mean because you said "RequestMapping" and then linked to "RequestParam". The guide text is wrong, though, so we should fix that.

**Comment by david-arteaga** [comment]
I meant RequestParam, sorry about that, and I read the javadoc wrong, . But the guide text as you say is incorrect.
On Sep 20, 2016 4:07 PM, Dave Syer <notifications@github.com> wrote:The javadoc says "true" is the default for the required attribute of @RequestParam. But I'm not sure I know what you mean because you said "RequestMapping" and then linked to "RequestParam". The guide text is wrong, though, so we should fix that.

**Comment by dsyer** [comment]
Fixed in spring-guides/gs-rest-service@c29a1de. Please raise issues with individual guides if you find any more.
