### ISSUE TITLE
Suffix Pattern Matching: greeting.bat are also matched in the example "Building a RESTful Web Service"

### ISSUE THREAD

**Issue by GingerMoon** [spring-guides/getting-started-guides#36]
According to the document:
By default Spring MVC performs ".*" suffix pattern matching so that a controller mapped to /person
is also implicitly mapped to /person.*. 

So the handler method @RequestMapping("/greeting") should not match with "greeting.bat".

https://spring.io/guides/gs/rest-service/

**Comment by dsyer** [comment]
The guide doesn't mention suffix matching at all. I think you misinterpreted the default behaviour, but this guide is probably not the best place to go into detail on that (the user guide would be).

**Comment by GingerMoon** [comment]
Dear Dave,
Thank you for your reply.
The document link: 
http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-requestmapping-suffix-pattern-match

Anyway, do you think this behavior ["/greeting.bat" matches @RequestMapping("/greeting")] is correct or not?
Regards,
Moon

**Comment by dsyer** [comment]
Thanks for the link. I think it confirms that suffix matching is on by default. As I said above, this guide is not a good place to discuss the details. If you want to quibble with the defaults or the documentation, please go to the Spring Framework JIRA.
