### ISSUE TITLE
The method setApplicationContext(ApplicationContext) is undefined for the type MessageDispatcherServlet

### ISSUE THREAD

**Issue by tusharbanne** [spring-guides/getting-started-guides#37]
```
public ServletRegistrationBean messageDispatcherServlet(ApplicationContext applicationContext) {
		MessageDispatcherServlet servlet = new MessageDispatcherServlet();
		servlet.setApplicationContext(applicationContext);
		servlet.setTransformWsdlLocations(true);
		return new ServletRegistrationBean(servlet, "/ws/*");
	}
```

In the above method, 
`servlet.setApplicationContext(applicationContext);`

gives an error 

> The method setApplicationContext(ApplicationContext) is undefined for the type MessageDispatcherServlet

when checked the API of MessageDispatcherServlet, there isn't  any method setApplicationContext.

Please Help.

**Comment by dsyer** [comment]
Which guide did you see this in? Each guide has its own gitthub repo, so please open an issue in the corresponding tracker.
