### ISSUE TITLE
Routing and Filtering

### ISSUE THREAD

**Issue by mycapgemini** [spring-guides/getting-started-guides#39]
In GatewayApplication properties file have wrong statement zuul.routes.books.url=http://localhost:8090. Here books should be replace by book

**Comment by dsyer** [comment]
Each guide has it's own repository and issue tracker. It's not clear from your description which one you mean. Can you find it and create a new issue?

**Comment by ryanjbaxter** [comment]
repo is here https://github.com/spring-guides/gs-routing-and-filtering/issues
