### ISSUE TITLE
Centralized Configuration - missing git command

### ISSUE THREAD

**Issue by assafsh2** [spring-guides/getting-started-guides#41]
Hi,

I succed to build client\server according to the guide of centralized configuration and found 2 issues
1.It's not clear that each parameters in the properties file must have method in the client, eg - 
param address=NY
and method -

    @RequestMapping("/address")
    String getAddress() {
        return this.address;
    }

2.To upload the a-bootiful-client.properties to the git, need to run first
git add a-bootiful-client.properties and than
git commit, 
otherwisw the server will not recoginze the file.

thanks,
Assaf

**Comment by ryanjbaxter** [comment]
Please open your issue here https://github.com/spring-guides/gs-centralized-configuration
