### ISSUE TITLE
Report possible content error

### ISSUE THREAD

**Issue by RSLi** [spring-guides/getting-started-guides#42]
On https://spring.io/guides/gs/handling-form-submission/, in the sample code of `src/main/java/hello/GreetingController.java`, `@ModelAttribute Greeting greeting` does not work unless it is written as `@ModelAttribute(value="greeting") Greeting greeting`

**Comment by dsyer** [comment]
Each guide has it's own github repository. That one is here: https://github.com/spring-guides/gs-handling-form-submission. But you don't need the `value=`, so there's something odd about your JVM probably. Did you try it with an up to data Java 8?

**Comment by RSLi** [comment]
Thanks a lot. I'm sure my JVM is up to date and will do some further investigation on that. Thanks!
