### ISSUE TITLE
Consuming a RESTful Web Service doesn't has info about nested list in a JSON

### ISSUE THREAD

**Issue by rossifederico** [spring-guides/getting-started-guides#54]
I'm currently working on a new spring based project and i had this problem again. It's very common (or for sure) consume APIs that the response looks like this:

`{ id: 123,
name: "foo",
vehicles: [
    {
        model: "sedan"
    },
    {
        model: "truck"
    } 
] }`

In order to support the "vehicles" list attribute, you must define your RestTemplate Bean like this:
`@Bean

    public RestTemplate restTemplate(){
        RestTemplate restTemplate = new RestTemplate();
        MappingJackson2HttpMessageConverter mappingJackson2HttpMessageConverter = new MappingJackson2HttpMessageConverter();
        mappingJackson2HttpMessageConverter.setSupportedMediaTypes(Arrays.asList(MediaType.APPLICATION_JSON, MediaType.TEXT_HTML));
        restTemplate.getMessageConverters().add(mappingJackson2HttpMessageConverter);
        return restTemplate;
    }`

There's a lot of questions (like [this](https://stackoverflow.com/questions/28893713/map-nested-json-objects-to-java-classes-with-spring-resttemplate)) in stackoverlow .

I really think that if you're writing a new app, probably you'll need to parse nested json and it's a problem if the Guide only provide the basic feature of plain jsons. If you think that it's a good idea, i can help with the new lines of the Guide. 

Thanks!
Regards,
Fede.

**Comment by dsyer** [comment]
That response is not JSON so it's not surprising it can't be unmarshalled using a JSON converter. What is this "embedded JSON" that you speak of? Where does it originate? Note that the SO link you pasted contains a question about unmarshalling actual JSON, so it doesn't look the same to me.

**Comment by rossifederico** [comment]
Thanks for the quicly response! 
I already corrected the example JSON (isn't my question, is another guy question).

If you try to parse a JSON with a nested list of JSONs with the default RestTemplate configuration throws the exception: 
> Could not extract response: no suitable HttpMessageConverter found for response type

**Comment by dsyer** [comment]
Works for me. Maybe you can post a sample app? Perhaps fork the actual consuming guide that you referred to and modify it?

**Comment by rossifederico** [comment]
It was a problem of the server API, the response has the wrong content-type. I'll close the issue, thanks!.
