### ISSUE TITLE
Java code blocks are broken

### ISSUE THREAD

**Issue by kugaudo** [spring-guides/getting-started-guides#58]
Here it is:
![screen shot 2017-11-27 at 15 45 45](https://user-images.githubusercontent.com/22676421/33269563-d0f29218-d389-11e7-884c-78783de744c9.png)

Steps to reproduce: go to any tutorial (e.g. https://spring.io/guides/gs/spring-boot/) and scroll to any Java code block.

P.S. It's already 5 days since I caught this trouble, I tried to report everywhere I could (contacted Spring team twitters / facebooks, Pivotal official support etc.). You guys have to improve feedback possibilities because there is **no public way** to contact you directly.
Thanks to Pivotal twitter I'm here.

**Comment by gregturn** [comment]
I see it for that guide. I checked two others and do NOT see it do something is unique about this guide.

**Comment by kugaudo** [comment]
@gregturn I might be wrong about about "any tutorial". It seemed to me I met the issue atleast two times  in a row.

**Comment by gregturn** [comment]
I cleared the cache for that guide and the code blocks rendered correctly. So it looks like certain guides maybe have been tripped by some GitHub issue. I have since cleared the caches for all guides so hopefully the issue is resolved. Thanks for alerting us.

**Comment by kugaudo** [comment]
@gregturn Thank you!
