### ISSUE TITLE
Typo in quick-start guide

### ISSUE THREAD

**Issue by astefan-pivotal** [spring-guides/getting-started-guides#6]
In this guide [1] there is a small typo issue with the <dependency /> artifact, which is wrong:
```
<dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-framework</artifactId>
        <version>4.0.5.RELEASE</version>
    </dependency>
```
and I believe it should actually be:
```
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-context</artifactId>
    <version>4.0.5.RELEASE</version>
</dependency>
```

There is no "spring-framework" artifact and the guide text mentions "spring-context" instead.

[1] https://github.com/spring-guides/getting-started-guides/issues

**Comment by gregturn** [comment]
Can you paste an exact link to the issue? I don't see anything other than Spring Boot starters in this template's complete/pom.xml file.
