### ISSUE TITLE
when i use eureka ,config-client enter /refresh is 404

### ISSUE THREAD

**Issue by naah69** [spring-guides/getting-started-guides#66]
i use config-server with eureka ,and config-client get config from eureka  by config-server's service-id.
i can get the value ,After i change the value from Git, i enter /fresh,it is error code 404.
i look for /fresh from log.it don't exist. 
i confirm that i use true POM.

config-server's POM use spring-boot-starter-web,spring-cloud-config-server,spring-cloud-starter-netflix-eureka-client.

config-client's POM use spring-boot-starter-web,spring-cloud-starter-config,spring-cloud-starter-netflix-eureka-client,spring-boot-starter-actuator

can you help me?

**Comment by gregturn** [comment]
This sounds like a perfect problem to post on stackoverflow.com where you can include all your build files.

**Comment by naah69** [comment]
thanks for your answer,i will ask it on stackoverflow

**Comment by naah69** [comment]
i find the answer.
it needs to be enabled And it is under  /actuator .
the full path is  /actuator/refresh
yml:
management:
  endpoints:
    web:
      exposure:
        include: refresh
