### ISSUE TITLE
Extend JMS guide to include e2e multi app network, and testing

### ISSUE THREAD

**Issue by xenoterracide** [spring-guides/getting-started-guides#76]
I've been having problems getting 2 spring boot jms apps to communicate with each other over network. I also have a strange problem with one of my tests failing randomly (the test times out after 5 minutes of not receiving the message), I'd like to see what's suggested for testing jms works.

**Comment by snicoll** [comment]
Guides are short and focused and extending the JMS one to handle such use case is not going in that direction. If you're having some trouble with your setup, please ask on StackOverflow.
