### ISSUE TITLE
Add non Spring-Boot powered guides

### ISSUE THREAD

**Issue by mdeinum** [spring-guides/getting-started-guides#9]
A couple of days ago [this](http://stackoverflow.com/questions/25823606/where-are-spring-tutorials-without-spring-boot) thread arose on StackOverflow. I think they have a point, although most of us like Spring Boot it would be nice to still have a couple of plain guides for Spring Framework (or related projects). Most projects still use plain Spring (with some of the portfolio projects) and not Spring Boot.

I think the current guides are great and really allow the reader to focus on the root content of the guide and not being distracted by the setup around that (datasources, connection factories etc.).

**Comment by gregturn** [comment]
Seeing no plans to write extra guides that are explicitly non-Boot, I am closing this issue.

**Comment by brettryan** [comment]
What happened to adding reference doc links to the pages relevant to the article? Existing articles do not have reference document links to the relevant pages, just to the project page. We need reference documentation links to provide more extensive support on the components within each guide.

**Comment by gregturn** [comment]
That idea is still in place. We just aren't necessarily going guide by guide right now. But don't forget, many of these guides do have links. For example, https://spring.io/guides/gs/scheduling-tasks has links to pertinent javadocs on configuring the scheduling annotations.

**Comment by brettryan** [comment]
Excellent. I was thinking more so about linking back to the actual reference documentation which is a fantastic set of docs but can be overwhelming for someone getting started. Links directly to the reference docs (not so much the API docs) are a necessity.

**Comment by gregturn** [comment]
@brettryan Sure thing. I guess if people open issues in key places, it is easier to track down.
